### ISSUE TITLE
Special character in permalink cause internal server error

### ISSUE THREAD

**Issue by Koli14** [frontity/frontity#432] opened 2020-05-11 11:52 UTC
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

**Expected behavior**

If I visit an URL with special character in the permalink, it should open the post.

**Observed behavior**

Internal Server Error:
```
TypeError: Cannot read property 'split' of undefined
      at __webpack_exports__.default (webpack-internal:///./node_modules/@frontity/wp-source/src/libraries/handlers/utils/capitalize.ts:2:73)
      at Object.eval (webpack-internal:///./node_modules/@frontity/wp-source/src/libraries/handlers/postType.ts:10:205)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at eval (webpack-internal:///./node_modules/@frontity/wp-source/src/actions.ts:18:101)
```

**Steps involved to reproduce the problem**

`npx frontity create` -> Create a WP post, with the title: `test♯post`, Publish it, than visit it through Frontity Frontend (e.g.: http://localhost:3000/test%E2%99%AFpost or http://localhost:3000/test♯post). If navigated to the page, than press enter on the address bar. 
Example: https://szinhaz.online/test%E2%99%AFpost2

**Info about your system**

## System:
 - OS: Linux 5.3 Linux Mint 19.3 (Tricia)
 - CPU: (8) x64 Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz
 - Memory: 7.36 GB / 15.54 GB
 - Shell: 4.4.20 - /bin/bash
## Binaries:
 - Node: 12.16.3 - /usr/bin/node
 - npm: 6.14.5 - ~/.npm_modules/bin/npm
## Browsers:
 - Chrome: 81.0.4044.138
 - Firefox: 75.0
## npmPackages:
 - @frontity/core: ^1.5.3 => 1.5.3 
 - @frontity/html2react: ^1.3.2 => 1.3.2 
 - @frontity/mars-theme: ./packages/mars-theme => 1.4.1 
 - @frontity/tiny-router: ^1.2.0 => 1.2.0 
 - @frontity/wp-source: ^1.7.0 => 1.7.0 
 - frontity: ^1.6.0 => 1.6.0 
## npmGlobalPackages:
 - frontity: Not Found
 - npx: Not Found

**Possible solution**

**Comment by michalczaplinski** [comment] 2020-05-14 21:58
Thanks for the report @Koli14 ! 🙂 

I can reproduce this locally with a clean frontity project and a local WP backend.

~~Although, when running the `mars-them-example` from the frontity repo and pointing it to the same local WP instance, I'm not able to reproduce anymore.~~

~~Will need to investigate this further.~~

EDIT: I can reproduce it and found the cause.

**Comment by michalczaplinski** [comment] 2020-05-25 16:47
When using special characters in URLs like: `localhost:3000/test♯post`, the browser interprets the URL as `localhost:3000/test%E2%99%AFpost` **(note the uppercase in the percent-encoded characters)**

However, Wordpress works with lowercase slugs and will internally force them to lowercase!

Thus, `action.get()` will create an entry for `/test%E2%99%AFpost/` (**uppercase**) in the `source.data`. 

However, when trying to fetch the data from the REST API, `libraries.populate()` will get the data successfully, but because WP works with lowercase only, the data will have a slug like `/test%e2%99%afpost/` (**lowercase**). So, `populate()` will create another entry in `data`, this time for the lowercase url and the the uppercase URL in `source.data` will stay without any linked data!

So, when we get the this line: 

```
  // 2. get `type` and `id` from route data and assign props to data
  const { type, id } = state.source.get(route);
```

route is "uppercase", but there is no data for the uppercase version, only for the lowercase version. Therefore, `type` is `undefined`.

Subsequently calling ```[`is${capitalize(type)}`]: true``` fails because of that.

**Comment by michalczaplinski** [comment] 2020-05-25 21:02
Additionally, I would suggest to add a check around these lines:

https://github.com/frontity/frontity/blob/bcac7dca9b15711eb78f5c53d6817654cdca844f/packages/wp-source/src/libraries/handlers/postType.ts#L49-L51

because if the `const { type, id} = state.source.get(route)` fails to get the object, then the `type` is undefined and it means that we should throw a more meaningful error, perhaps informing the user that no data was found for a particular route.

**Comment by michalczaplinski** [comment] 2020-11-02 21:31
This was possibly fixed in https://github.com/frontity/frontity/pull/606. Were you able to confirm that @DAreRodz ?

**Comment by DAreRodz** [comment] 2020-11-03 10:28
My bad, I forgot to check that! Could you do a quick test, if you don't mind? :slightly_smiling_face:

**Comment by michalczaplinski** [comment] 2020-11-03 19:19
It does work fine indeed! 👍 👍 👍 

Confirming that this was fixed in #606 and will be available in the next release.

CC: @Koli14

**Closed as completed by michalczaplinski** 2020-11-03 19:19 UTC
Labels: bug, priority: medium

**Comment by luisherranz** [comment] 2020-11-04 09:25
Awesome guys 🙂

@michalczaplinski does it make sense to add unit tests for this to make sure we don't ever get this problem in the future?

**Comment by michalczaplinski** [comment] 2020-11-05 01:50
> Awesome guys 🙂
> 
> @michalczaplinski does it make sense to add unit tests for this to make sure we don't ever get this problem in the future?

Yup, PR here https://github.com/frontity/frontity/pull/611  :)

**Comment by luisherranz** [comment] 2020-11-05 07:42
Thanks Michal! 🙌
