### ISSUE TITLE
Getting warning about deprecated createFactory

### ISSUE THREAD

**Issue by w3bdesign** [frontity/frontity#384] opened 2020-04-23 23:44 UTC
**_Bug report_**

- (X) I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- (X) I've searched for existing issues.
- (X) I've checked the documentation: https://docs.frontity.org
- (X) I've checked the community forum: https://community.frontity.org

**Expected behavior**

I expect no errors or warnings

**Observed behavior**

I see the following after cloning the mars starter theme and running the dev server:

Warning: React.createFactory() is deprecated and will be removed in a future maj
or release. Consider using JSX or use React.createElement() directly instead.

**Steps involved to reproduce the problem**

1. npx frontity create my-app
2. Select "mars-theme"
3. cd my-app
4. npx frontity dev

https://github.com/frontity/frontity/tree/dev/examples/mars-theme-example

**Info about your system**

## System:
 - OS: Windows 7 6.1.7601
 - CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
 - Memory: 5.46 GB / 15.94 GB
## Binaries:
 - Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
 - npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
## Browsers:
 - Internet Explorer: 11.0.9600.19301
## npmPackages:
 - frontity: ^1.5.3 => 1.5.3 
## npmGlobalPackages:
 - frontity: Not Found
 - npx: Not Found

**Possible solution**

Use JSX?

**Comment by michalczaplinski** [comment] 2020-04-24 14:17
Hi @w3bdesign ! Thanks for reporting the issue! 🙂 

It looks like this issue is caused by a mars starter theme dependency `react-spinners`. 

React-spinners used to have a dependency on `recompose`. Recompose used the "old" `.createFactory()` API. However, I can see that they have already [removed `recompose` in 0.6.0 n August 2019](https://github.com/davidhu2000/react-spinners/releases/tag/0.6.0) so I'm not sure why we still get the old version.

In any case, it's an annoyance but it's not breaking anything (for the moment).

**Comment by michalczaplinski** [comment] 2020-04-24 16:28
@SantosGuillamot Should we add it to the new Sprint?

**Comment by luisherranz** [comment] 2020-04-24 18:31
Maybe we can get rid of `react-spinners`. I already did it in this repo: https://github.com/luisherranz/embed-files-in-node-server/blob/master/frontity/packages/mars-theme/src/components/loading.js

**Comment by michalczaplinski** [comment] 2020-04-24 18:37
> Maybe we can get rid of `react-spinners`. I already did it in this repo: https://github.com/luisherranz/embed-files-in-node-server/blob/master/frontity/packages/mars-theme/src/components/loading.js

Hell yeah, I'd rather do that 😄 

Also:

<img width="952" alt="Screenshot 2020-04-24 at 13 35 45" src="https://user-images.githubusercontent.com/5417266/80245545-87049c80-8630-11ea-8091-d3bf9df5b844.png">

vs.

<img width="484" alt="Screenshot 2020-04-24 at 13 36 12" src="https://user-images.githubusercontent.com/5417266/80245598-9be13000-8630-11ea-885a-33b3c44d493c.png">

**Comment by luisherranz** [comment] 2020-04-24 18:45
We are not importing the whole `react-spinner` library, only [one spinner](https://github.com/frontity/frontity/blob/dev/packages/mars-theme/src/components/loading.js#L3) so it's not that big, but yeah we could get rid of it 😄

**Comment by michalczaplinski** [comment] 2020-04-24 22:07
oh, I didn't realize that :) But still, let's get rid of it.

**Comment by w3bdesign** [comment] 2020-04-24 23:44
Can also replace with a CSS-only spinner if needed:

https://github.com/danielcardoso/load-awesome/

**Comment by SantosGuillamot** [comment] 2020-04-27 07:13
As far as I understood, it's something that is not breaking the page right now but it may in the future right? If so, I'm adding the label `priority: medium` and it'd be done this sprint only if we finish the issues that are already planned before ending the sprint and we don't find any more bugs with higher priority.

Anyway, it seems like a `good-first-issue`, would you be willing to contribute with a solution for this @w3bdesign ? :slightly_smiling_face:

**Comment by w3bdesign** [comment] 2020-04-27 08:55
@SantosGuillamot 

I can try, do you want to replace the spinner with a different implementation, or do you just want to remove it completely?

**Comment by SantosGuillamot** [comment] 2020-04-27 10:06
I would replace it with a css implementation as you suggested or @luisherranz did at [this repo](https://github.com/luisherranz/embed-files-in-node-server/blob/master/frontity/packages/mars-theme/src/components/loading.js). What do you think guys?

**Comment by luisherranz** [comment] 2020-04-27 11:10
My React component is an exact match, in case you want that 🙂

The loader of TwentyTwenty also needs to be changed: https://github.com/frontity/frontity/blob/dev/packages/twentytwenty-theme/src/components/loading.js

**Comment by luisherranz** [comment] 2020-04-28 05:49
We can also wait for a merge here:
https://github.com/acdlite/recompose/pull/795

**Comment by michalczaplinski** [comment] 2020-04-28 14:41
>We can also wait for a merge here:
acdlite/recompose#795

Let's not wait for a merge 🙂 Recompose is [not really maintained anymore](https://github.com/acdlite/recompose#a-note-from-the-author-acdlite-oct-25-2018) so who knows how long it will take.

@w3bdesign If you'd like to contribute, go ahead! You can remove the spinners and add [the component](https://github.com/luisherranz/embed-files-in-node-server/blob/master/frontity/packages/mars-theme/src/components/loading.js) mentioned by @SantosGuillamot or you can try to write your own with pure CSS!

**Comment by w3bdesign** [comment] 2020-04-28 17:16
@michalczaplinski 
I am out travelling, but I will take a quick look tomorrow.

**Comment by w3bdesign** [comment] 2020-04-29 23:33
@michalczaplinski 

https://github.com/frontity/frontity/pull/409

Sorry if I haven't followed community guidelines or done anything incorrectly, but I have made an attempt and attached a screenshot.

Feel free to let me know what you think!

**Comment by luisherranz** [comment] 2020-05-04 09:20
Fixed in https://github.com/frontity/frontity/pull/409.

**Comment by luisherranz** [comment] 2020-05-04 09:20
Thanks @w3bdesign!! 🎉 🎉

**Closed as completed by luisherranz** 2020-05-04 09:20 UTC
Labels: bug, good first issue, priority: medium
