### ISSUE TITLE
source.populate bug, even from documentation

### ISSUE THREAD

**Issue by millerf** [frontity/frontity#438] opened 2020-05-21 11:55 UTC
**_Bug report_**

Use documentation example:

https://docs.frontity.org/api-reference-1/wordpress-source#example

```
const response = libraries.source.api.get({ endpoint: "posts" });
libraries.source.populate({ response, state });
```

**Expected behavior**

I expect to populate with all my posts

**Observed behavior**

```
 (node:1) UnhandledPromiseRejectionWarning: TypeError: response.json is not a function
front_1      |     at Object.populate (webpack-internal:///./node_modules/@frontity/wp-source/src/libraries/populate.ts:9:27)
front_1      |     at eval (webpack-internal:///./packages/container-page/src/beforeSSR.js:11:307)
front_1      |     at process._tickCallback (internal/process/next_tick.js:68:7)
front_1      | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 84)
```

**Comment by michalczaplinski** [comment] 2020-05-21 15:16
Hi @millerf 👋 

Could you share more details to help us confirm this? 
Ideally, could you provide a repo / codesandbox with a reproduction of the bug?

Could you also share the URL of your WP REST API ?

**Comment by michalczaplinski** [comment] 2020-06-03 23:14
I'm going to close this issue as there is no way to reproduce this based on the initial information. 

I'm happy to re-open if more information is provided or the issue occurs again.

**Closed as completed by michalczaplinski** 2020-06-03 23:14 UTC

**Comment by DAreRodz** [comment] 2020-06-04 10:00
This looks like an problem in our documentation. `libraries.source.api.get` returns a `Promise` so in order to get the `response` object you need to use **`await`**.

```ts
const response = await libraries.source.api.get({ endpoint: "posts" });
```

I'm going to open an new issue in our documentation repository to fix this.

Thanks for your bug report, @millerf! :slightly_smiling_face:

**Comment by michalczaplinski** [comment] 2020-06-04 23:51
Oh nice catch, thanks @DAreRodz ! 🙂
