### ISSUE TITLE
Error after upgrading @frontity/wp-source to 1.5.0

### ISSUE THREAD

**Issue by mody-ydom** [frontity/frontity#265] opened 2020-01-14 22:56 UTC
**_Bug report_**

- [x] I've searched for existing issues
- [x] I've checked documentation: https://docs.frontity.org
- [x] I've checked community forum: https://community.frontity.org

**Describe the expected behavior**
getting the data from source as expected

**Describe the observed behavior**
strange error appears in the console when navigating to any page
```
TypeError: Cannot read property 'func' of null
    at eval (actions.ts?f1c8:46)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (actions.ts:6)
    at _next (actions.ts:6)
    at eval (actions.ts:6)
    at new Promise (<anonymous>)
    at eval (actions.ts:6)
    at eval (actions.ts?f1c8:12)
    at Object.eval [as fetch] (create-store.js?81b0:27)
    at eval (actions.ts?fe69:18)
```

**Describe the steps involved to reproduce the problem**
upgrade the wp-source by running this command
`npm install @frontity/wp-source@latest`

**Add info about your system**

## System:
 - OS: Windows 10 10.0.18362
 - CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
 - Memory: 2.72 GB / 15.89 GB
## Binaries:
 - Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
 - npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD
## Browsers:
 - Edge: 44.18362.449.0
 - Internet Explorer: 11.0.18362.1
## npmPackages:
 - bootstrap: ^4.4.1 => 4.4.1 
 - frontity: ^1.4.4 => 1.4.4 
 - prop-types: ^15.7.2 => 15.7.2 
 - react: ^16.12.0 => 16.12.0 
 - react-slick: ^0.25.2 => 0.25.2 
 - react-spinners: ^0.7.2 => 0.7.2 
 - react-spring: ^8.0.27 => 8.0.27 
 - slick-carousel: ^1.8.1 => 1.8.1 
## npmGlobalPackages:
 - frontity: Not Found
 - npx: Not Found

it was working will before updating to 1.5.0 to use REST API - Head Tags

**Comment by luisherranz** [comment] 2020-01-15 08:56
Thanks for reporting @mody-ydom. Do you have a repo we could take a look at?

**Comment by luisherranz** [comment] 2020-01-15 09:35
@mody-ydom:
- What settings of `wp-source` are you using?
- Are you using handlers?

**Comment by mody-ydom** [comment] 2020-01-15 12:00
yes I'm using one handler

handler:
```javascript
const acfOptionsHandler = {
  name: 'acfOptionsHandler',
  pattern: 'acf-options-page',
  func: async ({route, state, libraries}) => {
    // 1. Get ACF option page from REST API.
    const response = await libraries.source.api.get({
      endpoint: `/acf/v3/options/options`,
    });
    const option = await response.json();
    
    // 2. Add data to `source`.
    const data = state.source.get(route);
    Object.assign(data, {...option, isAcfOptionsPage: true});
  },
};
```

processors:
```javascript
const changeEmptyPToBrProcessor={
  // We can add a name to identify it later.
  name: 'p2br',
  
  // We can add a priority so it executes before or after other processors.
  priority: 10,
  
  // Only process the node it if it's an image.
  test: node => node.component === 'p' && node.children.length === 0,
  
  process: (node) => {
    node.component = 'br';
    return node;
  },
  
};
```

my theme settings:
```javascript
export default {
  roots: {
    theme: Theme, 
    clipPaths: SvgDefs,
  },
  state: {
    theme: {
      icons: {},
    },
    source: {
      postTypes: [
        {
          type: 'icons',
          endpoint: 'icons',
        },
      ],
    },
  },
  actions: {
    theme: {
      addIcon: ({state}) => (icon) => Object.assign(state.theme.icons, icon),
      init: ({libraries}) => {
        libraries.source.handlers.push(
          acfOptionsHandler,
        );
        libraries.html2react.processors.push(
          changeEmptyPToBrProcessor,      
        );
      },
      beforeSSR: async ({actions}) => {
        // This will make Frontity wait until the ACF options
        // page has been fetched and it is available
        // using state.source.get("acf-options-page").
        await actions.source.fetch('acf-options-page');
      },
    },
  },
  libraries: {
    theme: {
      lightenDarkenColor,
    },
    source: {
      // Add the custom handler for ACF options defined above.
      // handlers: [acfOptionsHandler, acfIconsHandler],
    },
  },
};
```

**Comment by mody-ydom** [comment] 2020-01-15 12:02
> Thanks for reporting @mody-ydom. Do you have a repo we could take a look at?

sorry I can't share the whole repo now as my client doesn't want to share it

**Comment by luisherranz** [comment] 2020-01-15 18:36
Thanks @mody-ydom. We'll take a look. 

Just to be sure: does the site work (but you see errors on the console)?

**Comment by mody-ydom** [comment] 2020-01-15 18:37
no data is fetched so the site is empty @luisherranz

**Comment by luisherranz** [comment] 2020-01-15 18:38
For anything or for the custom handler?

**Comment by mody-ydom** [comment] 2020-01-16 11:12
Thank you @SantosGuillamot 
that was amazing 👍 

Thank you @luisherranz for your care :)

**Comment by SantosGuillamot** [comment] 2020-01-16 11:21
Glad it worked 🙂 Keep us updated if you find more issues!

**Comment by luisherranz** [comment] 2020-01-20 09:14
It's fine that you were able to solve it guys, but this should not have happened in the first place. 

@SantosGuillamot I'd love to try to reproduce the problem with you. I want to find the root cause.

**Comment by luisherranz** [comment] 2020-01-20 09:15
I'm going to leave this issue open until we find the problem. @mody-ydom feel free to unsubscribe.

**Comment by luisherranz** [comment] 2020-02-11 15:03
After some tests, we were not able to reproduce this issue so I'm going to close it again.

If someone else sees this problem in the future please let us know and add steps here on how to reproduce the problem.

**Comment by SantosGuillamot** [comment] 2020-02-25 15:13
I run into the same problem after trying to update blog.frontity.org, so I'm reopening the issue. Here we have the steps to reproduce the problem:

We have the blog.frontity.org repo (https://github.com/frontity/blog.frontity.org).
1. We have to go to the status previous to the release: clone it to your computer and checkout `master`, before updating the dependencies. Delete your `node_modules` if you have (it was my case) and run `npm install`. (At this point, we should be at the status before the update, and `npx frontity dev` works properly.
2. Run these commands to update Frontity as recommended in our guide: `npx npm-check-updates -u` and `npm install`. At this point, I expected everything to work, but if I run `npx frontity dev` I get an Internal Server Error.
3. If I delete `node_modules` and the `package-lock` and run `npm install`, the command `npx frontity dev` works now.

**Comment by luisherranz** [comment] 2020-02-25 20:43
If this is happening every single time someone updates Frontity I guess it's more serious than medium. Maybe we should investigate when this is happening to be able to prioritize it properly, don't you think?

**Comment by SantosGuillamot** [comment] 2020-02-26 08:27
I assumed that they were isolated cases, but I agree that if it happens on each update its priority should be higher. I'll change the label to `awaiting-triage`, although I'm not sure how to investigate it.

**Comment by DAreRodz** [comment] 2020-02-26 14:50
Doing a bit of debugging I saw that in [this line in connect.js](https://github.com/frontity/frontity/blob/dev/packages/connect/src/connect.js#L48), `useContext` is returning `undefined`. Is it supposed to do that?

**Comment by luisherranz** [comment] 2020-02-26 19:19
No, but that is new, right?

The OP talks about this error: `TypeError: Cannot read property 'func' of null`

What error are you getting? Is it not the same?

**Comment by luisherranz** [comment] 2020-02-27 08:40
`Sprint 0 (finished) automation moved this from Done to In progress 2 days ago`

We have to be careful with this 👆

Can you please take a look at our automations?

**Comment by luisherranz** [comment] 2020-02-27 19:21
After reviewing this with @orballo I think I understand better the problem: `@frontity/connect` must be installed only once.

Right now, it is installed on:
- `frontity`
- `@frontity/core`
- `@frontity/wp-source`

The only package of those three that is guaranteed to be installed only once is `@frontity/core` so we have to remove it from the other two, from dependencies to devDependencies.

@SantosGuillamot my opinion is that we should fix this in this sprint because it is forcing people to remove `node_modules` and the `package-lock.json` each time they update Frontity.

**Comment by SantosGuillamot** [comment] 2020-02-28 07:47
> Can you please take a look at our automations?

Sure, I guess that if a `done` issue is reopened it should go back to the `to-do` column, not to `in-progress`.

> @SantosGuillamot my opinion is that we should fix this in this sprint because it is forcing people to remove `node_modules` and the `package-lock.json` each time they update Frontity.

Yes, I agree that if this is happening on every update, and it's "breaking" Frontity, it should be fixed.

**Closed as completed** 2020-03-02 12:28 UTC
Labels: bug, priority: critical
