### ISSUE TITLE
Homepage with subdirectory returning 404

### ISSUE THREAD

**Issue by TiborUdvari** [frontity/frontity#833] opened 2021-05-27 21:31 UTC
**_Bug report_**

I needed to update all my packages to be able to use the `yoast` plugin. I have a multilanguage site using WPML in the backend. After updating frontity does not recognize my homepage anymore and returns a 404 page. Might be related to #806 

**Expected behavior**

I'm expecting it to return the homepage.

**Observed behavior**

A 404 page is returned.

**Steps involved to reproduce the problem**

You can pull the SEO branch over here. https://github.com/TiborUdvari/gama-website/tree/seo

The main branch has a running deployment here: https://gama-am.ch/fr/ 
You can consult it to see how the language routing works.

**Info about your system**

```
## System:
 - OS: macOS 11.1
 - CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
 - Memory: 202.33 MB / 32.00 GB
 - Shell: 5.8 - /bin/zsh
## Binaries:
 - Node: 12.18.2 - /usr/local/bin/node
 - npm: 6.14.10 - /usr/local/bin/npm
## Browsers:
 - Chrome: 90.0.4430.212
 - Edge: Not Found
 - Firefox: 84.0.1
 - Safari: 14.0.2
## npmPackages:
 - @frontity/components: ^1.7.3 => 1.7.3 
 - @frontity/core: ^1.14.1 => 1.14.1 
 - @frontity/html2react: ^1.7.0 => 1.7.0 
 - @frontity/tiny-router: ^1.4.2 => 1.4.2 
 - @frontity/wp-source: ^1.11.5 => 1.11.5 
 - @frontity/yoast: ^2.1.1 => 2.1.1 
 - @n8tb1t/use-scroll-position: ^2.0.3 => 2.0.3 
 - @nivo/bar: ^0.70.1 => 0.70.1 
 - @nivo/core: ^0.70.1 => 0.70.1 
 - @nivo/scatterplot: ^0.70.1 => 0.70.1 
 - @theme-ui/color: ^0.9.1 => 0.9.1 
 - @theme-ui/components: ^0.9.1 => 0.9.1 
 - @theme-ui/match-media: ^0.9.1 => 0.9.1 
 - @theme-ui/presets: ^0.9.1 => 0.9.1 
 - axios: ^0.21.1 => 0.21.1 
 - dotenv-webpack: ^7.0.2 => 7.0.2 
 - framer-motion: ^4.1.17 => 4.1.17 
 - frontity: ^1.16.0 => 1.16.0 
 - frontity-starter-theme: ./packages/frontity-starter-theme => 1.0.0 
 - hex-to-rgba: ^2.0.1 => 2.0.1 
 - highcharts: ^9.1.0 => 9.1.0 
 - highcharts-react-official: ^3.0.0 => 3.0.0 
 - i18next: ^20.3.0 => 20.3.0 
 - i18next-browser-languagedetector: ^6.1.1 => 6.1.1 
 - i18next-http-backend: ^1.2.6 => 1.2.6 
 - lodash: ^4.17.21 => 4.17.21 
 - luxon: ^1.27.0 => 1.27.0 
 - masonic: ^3.4.1 => 3.4.1 
 - nanoid: ^3.1.23 => 3.1.23 
 - navbar-demo:  0.0.1 
 - polished: ^4.1.2 => 4.1.2 (3.7.1)
 - react-cookie: ^4.0.3 => 4.0.3 
 - react-error-boundary: ^3.1.3 => 3.1.3 
 - react-ga: ^3.3.0 => 3.3.0 
 - react-headroom: ^3.1.1 => 3.1.1 
 - react-helmet-async: ^1.0.9 => 1.0.9 
 - react-hook-form: ^7.6.8 => 7.6.8 
 - react-html-parser: ^2.0.2 => 2.0.2 
 - react-html-parser-demo:  0.0.0 
 - react-i18next: ^11.9.0 => 11.9.0 
 - react-lottie: ^1.2.3 => 1.2.3 
 - react-move: ^6.4.0 => 6.4.0 
 - react-papaparse: ^3.14.0 => 3.14.0 
 - react-scroll: ^1.8.2 => 1.8.2 
 - react-share: ^4.4.0 => 4.4.0 
 - react-slugify: ^2.0.3 => 2.0.3 
 - react-swipeable-views: ^0.13.9 => 0.13.9 
 - react-table: ^7.7.0 => 7.7.0 
 - recaptcha-v3: ^1.9.1 => 1.9.1 
 - styled-components: ^5.3.0 => 5.3.0 
 - styled-components/macro:  undefined ()
 - styled-components/native:  undefined ()
 - styled-components/primitives:  undefined ()
 - theme-ui: ^0.9.1 => 0.9.1 
 - url-parse: ^1.5.1 => 1.5.1 
## npmGlobalPackages:
 - frontity: Not Found
 - npx: Not Found
```

**Possible solution**

Any quick hacks are welcome. I need to get it working again so I can finish this project.

**Comment by luisherranz** [comment] 2021-05-28 09:32
@TiborUdvari you need to isolate your problem. We can't inspect such a huge project that we are not familiar with.

As you have a moment in your git history where it worked, and then the moment when it broke, I suggest you to go back to the moment where it worked and repeat your steps until you find the exact moment when the bug started.

Once you have that information, we can analyze and fix the bug.

It would also be really helpful if after finding the exact cause of your bug, you could reproduce it in a clean Frontity project using `mars-theme` and either codesandbox or stackblitz, then share it here. You can use this template: https://github.com/frontity/frontity-template

Feel free to reopen this issue once you have it. Thanks 🙂

**Comment by TiborUdvari** [comment] 2021-05-28 10:08
Hi,

I updated these packages following your guide [Keep frontity updated](https://gitbook-docs.frontity.org/guides/keep-frontity-updated)

Before (working)
```js
     @frontity/core": "^1.9.0",
    "@frontity/html2react": "^1.4.0",
    "@frontity/tiny-router": "^1.2.2",
    "@frontity/wp-source": "^1.9.1",
```

After(homepage 404 with subdirectory setting) 
```js
    "@frontity/components": "^1.7.3",
    "@frontity/core": "^1.14.1",
    "@frontity/html2react": "^1.7.0",
    "@frontity/tiny-router": "^1.4.2",
    "@frontity/wp-source": "^1.11.5",
    "@frontity/yoast": "^2.1.1",
```

Here are the relevant settings from `frontity.settings` which were working before:
`frontity.settings.js`

```
...
source: {
            api: "https://MY_SITE/fr/wp-json",
            url: "https://MY_SITE", 
            subdirectory: "/fr",
            homepage: "/fr/homepage",
...
```

The only thing I need help with is this 404 error from `wp-source` on the homepage. The other pages get the data fine. All other project related things are irrelevant.

It works fine without the `subdirectory` setting but that way I can't have it multi-language. 

Could you tell me how I could get the route that `frontity` is using to return as the homepage in order to debug? 

Can I use my wp backend if I want to try to reproduce the problem for you?

**Comment by luisherranz** [comment] 2021-05-28 10:15
> Could you tell me how I could get the route that frontity is using to return as the homepage in order to debug?

I think it is `state.source.homepage`.

By the way, have you tried using: 

```js
{
  source: {
    subdirectory: "/fr",
    homepage: "homepage"
  }
}
```

> Can I use my wp backend if I want to try to reproduce the problem for you?

Sure, that's totally fine, but use a clean Frontity project with just the modifications that lead to the bug 🙂

**Comment by TiborUdvari** [comment] 2021-05-28 11:40
Yes, I've tried `/fr/homepage`, `homepage`, `/homepage` ... doesn't seem to work. The `router.state.link` is `/fr/` which is to be expected. The mapping of this route doesn't happen to the homepage.

I'll try to setup a minimal example.

**Comment by TiborUdvari** [comment] 2021-05-28 12:11
Here it is:

https://codesandbox.io/s/frontity-subdirectory-homepage-bug-8twui?file=/frontity.settings.js

I added an example with the working config, that doesn't use the `subdirectory` and my desired, but non working config. 

```js
    {
      name: "@frontity/wp-source",
      state: {
        source: {
          url: "BACKEND_URL",
          subdirectory: "/fr",
          homepage: "/fr/homepage",
          api: "BACKEND_URL/fr/wp-json"

          // Working config
          /*
          url: "https://backend.gama-am.ch/fr/",
          homepage: "/homepage"
          */
        }
      }
```

**Comment by luisherranz** [comment] 2021-05-28 13:34
Thanks a lot, that's much more helpful 🙂

Defining `state.source.api` is deprecated, you should only define `state.source.url`.

Docs: https://api.frontity.org/frontity-packages/features-packages/wp-source#state-source-api

It works for me with these settings:

```js
{
  state: {
    source: {
      url: "https://backend.gama-am.ch/fr",
      subdirectory: "/fr",
      homepage: "homepage",
   },
  },
};
```

Is there a reason why you need to define both `state.source.url` and `state.source.api`?

**Comment by TiborUdvari** [comment] 2021-05-28 14:03
With this config the `/fr/` homepage works as expected, but it makes it so the other pages don't work anymore, like `/fr/contact`. I can't find a way to make both cases work at the same time.

I have no particular reason to use both `source.url` and `source.api`, I was just trying out all the possibilites, and also I started with a starter project that had those defined.

**Comment by luisherranz** [comment] 2021-05-31 13:24
> With this config the /fr/ homepage works as expected, but it makes it so the other pages don't work anymore

I see, thanks 🙂

@darerodz, could you please help us figure out what is the correct configuration?

The docs for [`subdirectory`](https://api.frontity.org/frontity-packages/features-packages/wp-source#state-source-subdirectory) say that:

> It also transform links of the entities that come from the REST API.

So this setting is transforming the normal pages, like `/fr/contact` to `/contact`, but their links are `/fr/contact`. So even if Frontity [finds them in the REST API](https://backend.gama-am.ch/fr/wp-json/wp/v2/pages?slug=contact) becaues the slug is correct, it think they are not valid because the link doesn't match.

Codesanbdox: https://codesandbox.io/s/frontity-subdirectory-homepage-bug-forked-ioq6d?file=/frontity.settings.js

**Comment by TiborUdvari** [comment] 2021-06-07 08:57
Are there any suggestions on this issue? I think it's a deal breaker for many people that need to make multi-language websites. 😬 For now I managed to do a manual handler, but it defeats the purpose of using frontity ...

**Comment by luisherranz** [comment] 2021-06-08 05:46
@DAreRodz, any insights on this one? 😄

**Comment by DAreRodz** [comment] 2021-06-09 06:45
I was busy these days, sorry. Looking into it right now. :detective:

**Comment by DAreRodz** [comment] 2021-06-09 07:34
I see ~~two~~ **one** problem here:

- ~~The `Link` component seems to remove the subdirectory (e.g. `/fr/contact` -> `/contact`) so it is not navigating to the correct URL. That's unexpected. :confused:~~ Ok, this one was because `state.frontity.url` needs to be specified. That property should contain the final URL of the Frontity site, including the subdirectory. That's where the subdirectory is extracted from inside the `Link` component.

1. It is true, as @luisherranz said, that the `subdirectory` property modifies entity links, but replacing the WordPress subdirectory by the value you specified as subdirectory. In your case, as the value of `source.url` is `https://backend.gama-am.ch/fr`, the WordPress subdirectory is `/fr`, and that's replaced by `source.subdirectory` ―which is `/fr` again― so links should remain the same.
   Well, I saw that both the `about-us` and the `contact` packages have a link without `/fr`, so the link transform is not working in those cases.

**Comment by luisherranz** [comment] 2021-06-10 08:01
> Well, I saw that both the about-us and the contact packages have a link without /fr, so the link transform is not working in those cases.

Is that a bug?

**Comment by DAreRodz** [comment] 2021-06-10 09:05
> Is that a bug?

I wouldn't say it's a bug.

The `@frontity/wp-source` package works this way: if your WordPress site contains a subdirectory (e.g. `https://backend.gama-am.ch/fr`), it expects all links coming from the REST API to start with that subdirectory (`/fr`, `/fr/about-us`, `/fr/contact`, etc).

Then, the package transforms those links, either removing the WordPress subdirectory or replacing it with the value of `source.subdirectory`, in the case you are defining a subdirectory for you Frontity site.

@TiborUdvari, just to understand your use case, is there any reason why you would need those links not to have the `/fr` subdirectory when they come from the WordPress REST API?

**Comment by TiborUdvari** [comment] 2021-06-10 11:26
I'm not sure why it does that. The use case is having these pages working:

`/fr/` - french homepage
`/fr/about-us/` - french about us (validate if working: title is A propos)
`/en/` - english homepage
`/en/about-us/` - en about us page

I can't get the configuration to have the homepage and all of these use cases working.

**Comment by DAreRodz** [comment] 2021-06-14 12:26
OK, the thing is, setting `state.frontity.url` and `state.source.subdirectory`, Frontity should work for this use case:

```js
// Other props/packages were removed to simplify the code.
const settings = {
  name: "codesandbox-frontity",
  state: {
    frontity: {
      // The `/fr` subdirectory should be included in the Frontity URL.
      url: "https://gama-am.ch/fr",
    }
  },
  packages: [
    {
      name: "@frontity/wp-source",
      state: {
        source: {
          url: "https://backend.gama-am.ch/fr",
          subdirectory: "/fr",
          homepage: "homepage"
        }
      }
    }
  ]
};

export default settings;
```

In your case, however, the problem is that links come from the REST API with an unexpected format, i.e. not including the subdirectory. For example, requesting the Contact page, the link of the page entity is `https://backend.gama-am.ch/contact/`, but Frontity is expecting it to be `https://backend.gama-am.ch/fr/contact/`.

![Screenshot from 2021-06-14 14-15-50](https://user-images.githubusercontent.com/6917969/121891222-7a9f3f80-cd1b-11eb-9f9f-2d49c327092f.png)

I hope the WPML plugin has an option to fix that, that would be the best solution.

@TiborUdvari could you check that? :slightly_smiling_face:

**Comment by luisherranz** [comment] 2021-06-28 07:09
@TiborUdvari a friendly reminder here to see if you tried David's proposed solution 🙂

**Comment by luisherranz** [comment] 2021-07-12 10:52
I'm going to close this for now. @TiborUdvari, please reopen it again if you happen to try out what David suggested and it didn't work.

**Closed as completed by luisherranz** 2021-07-12 10:52 UTC
Labels: awaiting-triage
