### ISSUE TITLE
npx frontity dev: warning componentWillMount

### ISSUE THREAD

**Issue by afatoga** [frontity/frontity#181] opened 2019-08-18 09:42 UTC
While running npx command server writes this:

Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move code from componentWillMount to componentDidMount (preferred in most cases) or the constructor.

Please update the following components: SideEffect(NullComponent)

**Comment by luisherranz** [comment] 2019-08-19 15:15
Thanks for the report @afatoga.

Could you please describe the steps involved to reproduce the problem?

**Comment by afatoga** [comment] 2019-08-20 15:17
windows 10 machine (20-08-2019) reproduced: 
**npx frontity create my-app**
then I relocated to the folder my-app and ran this command:
**npx frontity dev**

which launched the dev interface + wrote that warning

**Comment by luisherranz** [comment] 2019-08-20 15:20
Thanks @afatoga.

Could you please run `npx frontity info` in the `my-app` folder? Then paste the result here.

**Comment by luisherranz** [comment] 2019-08-24 13:44
I've managed to reproduce it here @afatoga. There's no need for your `npx frontity info` anymore, thanks :)

This is caused by `react-helmet`: https://github.com/nfl/react-helmet/issues/426

I think we can safely switch to https://github.com/staylor/react-helmet-async

**Comment by hejamartin** [comment] 2019-09-04 10:04
Will this be addressed  in a nearby future? I did install a frontity just at this vdry moment. 

Your note that "we can safely switch to..." - do you mean that you will do this in the Frontity code her at github, or do I need to do it manually somehow in my own installation?

**Comment by luisherranz** [comment] 2019-09-04 11:05
> Will this be addressed in a nearby future?

Yes, it's something we want to get fixed in the next release.

> Your note that "we can safely switch to..." - do you mean that you will do this in the Frontity code her at github, or do I need to do it manually somehow in my own installation?

Frontity code as `react-helmet` is an internal tool.

**Closed as completed** 2019-09-09 16:45 UTC
Labels: bug
