### ISSUE TITLE
Some fields in Data are not populated when visiting a category on the client side

### ISSUE THREAD

**Issue by orballo** [frontity/frontity#428] opened 2020-05-08 10:15 UTC
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

**Expected behavior**

Data related to the route like `route`, `link` and `page` should be populated on client side.

<img width="490" alt="Screen Shot 2020-05-08 at 19 10 53" src="https://user-images.githubusercontent.com/13615057/81396134-ccac8380-915f-11ea-9a46-dc5f9ec639a8.png">

**Observed behavior**

That data is not populated.

<img width="479" alt="Screen Shot 2020-05-08 at 19 11 04" src="https://user-images.githubusercontent.com/13615057/81396150-d209ce00-915f-11ea-8093-858966e087ee.png">

**Steps involved to reproduce the problem**

Go to https://mars.frontity.org and visit a category. Then type `frontity.state.source.get(frontity.state.router.link)` on the console to get the value of data.

**Info about your system**

Irrelevant.

**Possible solution**

Don't know, haven't explored the issue in depth.

**Comment by luisherranz** [comment] 2020-05-08 10:19
Yes, thanks for the issue @orballo. If I'm not mistaken this is a duplicate of https://github.com/frontity/frontity/issues/365 so I'm going to close this one.

Feel free to reopen if you think this is different.

**Closed as completed by luisherranz** 2020-05-08 10:19 UTC
Labels: bug, duplicate
