### ISSUE TITLE
Internal server error when API endpoint contains "name" property

### ISSUE THREAD

**Issue by khnn** [frontity/frontity#614] opened 2020-11-05 21:05 UTC
**_Bug report_**

**Expected behavior**

If "name" is used internally or "name" is not valid as a property, it would be nice to receive a warning or error message suggesting to change the naming in the API endpoint.

**Observed behavior**

On the CPT archive page the frontend gives "Internal server error" and the console logs:
`TypeError: "Cannot read property '55' of undefined` for a post with ID 55.
On other pages containing posts of the CPT the console logs:
`{ ServerError: post type from endpoints "posts,pages,media" with slug "css2" not found`
...
` name: 'ServerError', status: 404,`

**Steps involved to reproduce the problem**
Add a property called 'name' to an API endpoint like mentioned here: https://www.youtube.com/watch?v=3Bab5jLuL1A&t=690s

**Possible solution**
Renaming the property solved it.

Just came across this great project. Thank you for all the work's being done here. If this bug won't be fixed, I thought this might be at least helpful to someone.

**Comment by michalczaplinski** [comment] 2020-11-06 01:03
Hi @khnn, thanks for reporting this! 

Could you help me reproduce it so that we can fix it? :) Could you post the code that you have used to "add" the `name` property in WordPress? Have you based it on the "vinyl" plugin code from the frontity talk?

Are you also able to share your frontity project here?

I'm asking this because I notice that `name` is one of the "reserved names" in WordPress that should not be used in certain circumstances as it might conflict with WP built-ins: https://codex.wordpress.org/Reserved_Terms, so I want to confirm that this is indeed a Frontity issue 🙂

**Comment by khnn** [comment] 2020-11-06 08:49
Edit: Yes, I have based it on the vinyl plugin code. 

Hey @michalczaplinski, Thank you for getting back to me and thanks for mentioning the reserced terms of wordpress. Here's my code adding the property:

  `public function add_fields_to_rest_api($data, $post, $request) {`
   `$_data = $data->data;`
...
    `$_data['name] = get_field('name', $post->ID);`
...
    `$data->data = $_data;`
    `return $data;`
  `}`

The API though, works as espected and returns the propery value from ACF.

**Comment by michalczaplinski** [comment] 2020-11-06 23:34
Thanks @khnn I can confirm that this is indeed an issue in Frontity. We'll work on it and update you in this thread.

The problem is in that line: https://github.com/frontity/frontity/blob/5d2d73882255e1b3ecf4895b269cdb78575ef11d/packages/wp-source/src/libraries/schemas/index.ts#L23

We check if the response for an entity has a `name` and if it does, we assume that it's an author, but in this case it's actually a custom post type, because you have added a `name` property to your Custom Post Type.

I'm not sure what the right fix for this should be. I don't see any other attributes for an author that we can use to disambiguate author from other entities when I look at the output of the REST API for for https://test.frontity.org/wp-json/wp/v2/users for example.

CC: @luisherranz

**Comment by khnn** [comment] 2020-11-07 09:09
Thank you so much for the update and the effort.

**Comment by luisherranz** [comment] 2020-11-09 09:06
Interesting. We want to get rid of the schemas but it's going to take a while.

@khnn is there a way you can change that field name in the meanwhile?

**Comment by khnn** [comment] 2020-11-09 09:13
Hey @luisherranz, absolutely. I can use that workaround I mentioned. Sorry, if that wasn't clear. Thank you for the effort.

**Comment by luisherranz** [comment] 2020-11-09 10:13
Awesome 🙂

We will make sure that this works again in the next version of Source, which won't use schemas anymore.

I'm going to close this for now, but feel free to reopen it if something else related arises.

**Closed as completed by luisherranz** 2020-11-09 10:13 UTC
Labels: bug
