### ISSUE TITLE
Infinite Scroll Hooks: Restoring scroll when going back and forward in Firefox

### ISSUE THREAD

**Issue by luisherranz** [frontity/frontity#751] opened 2021-03-12 16:03 UTC
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

**Expected behavior**

When going back to a page that was using an Infinite Scroll hook, the page and scroll should be restored in the exact same position where the user was before.

This works in Chrome, but it doesn't work in Firefox.

**Observed behavior**

Right now, the scroll is not restored in Firefox so it jumps to another page and position on the screen.

**Steps involved to reproduce the problem**

Some of our e2e tests are failing because of that.

I have made a video to show it: https://www.loom.com/share/4059b587de204a078f6f9256d89ca475

**Possible solution**

I don't know yet, needs more investigation to see why Firefox is not restoring the scroll.

**Comment by SantosGuillamot** [comment] 2021-03-15 11:53
I guess this may be related to this other bug opened some months ago right? -> [Scroll restoration when going back in history doesn't work in Firefox](https://github.com/frontity/frontity/issues/427).

Should we keep only one issue?

**Comment by SantosGuillamot** [comment] 2021-03-15 12:06
By the way, I tried to reproduce it in our blog, which is using the Infinite Scroll, but I wasn't able. In this case, it is weird as well but it goes back to the correct page but some pixels below the expected position. I've made a video showing it.

https://www.loom.com/share/15f1e25e15ac4307b2823578867354a5

I have tested it in my laptop (Ubuntu) and in BrowserStack Live (with macOS Catalina), and in both cases happens the same.

**Comment by luisherranz** [comment] 2021-03-16 17:15
Yes, it is certainly weird. I am not able to reproduce the problem described in https://github.com/frontity/frontity/issues/427 anymore either.

Let's talk over that issue.

**Comment by DAreRodz** [comment] 2021-04-27 18:14
I'm not sure but, after spending some days investigating, it looks like a problem related to Frontity running inside an iframe. I recorded a video showing it:

<a href="https://www.loom.com/share/5b38acfef1a9452ab601c17e52507517"> <p>Infinite Scroll Hooks: Restoring scroll when going back and forward in Firefox · Issue #751 · frontity/frontity - Watch Video</p> <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/5b38acfef1a9452ab601c17e52507517-with-play.gif"> </a>

As far as I know, there wouldn't anything we can do here ― apart from implementing our own scroll restoration behavior, which I think it isn't worth it. Or skipping the tests for Firefox, which is something we're already doing. :shrug:

@SantosGuillamot what do you think? How should we proceed here?

**Comment by luisherranz** [comment] 2021-04-28 07:47
Great discovery David! 🙂

My opinion is that we can close this. It clearly seems like a Firefox problem, not ours, and a marginal one because only affects apps run inside iframes.

**Comment by SantosGuillamot** [comment] 2021-04-28 07:55
Thanks for the detailed explanation David :slightly_smiling_face: 

I agree that it doesn't seem to be a Frontity issue and it isn't a big deal anyway. As we are all aligned I'm closing it.

**Closed as completed by SantosGuillamot** 2021-04-28 07:55 UTC
Labels: bug, priority: medium
