### ISSUE TITLE
Navigating to a Server Side Rendered url with an extension, `.html`,  shows 404 page

### ISSUE THREAD

**Issue by cristianbote** [frontity/frontity#727] opened 2021-02-24 08:50 UTC
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

**Expected behavior**

Navigating to a Server Side Rendered url with an extension should work.

**Observed behavior**

It shows a 404 page.

**Steps involved to reproduce the problem**

* Start a local wordpress site with permalinks configured to contain the `.html` extension
* Go to any local frontity project
* Use the local wordpress api
* Navigate to a post
* Do a full refresh on the same post

This bug was reported in this community discussion https://community.frontity.org/t/404-error-after-updating-original-post-from-wordpress-panel/3996/21

**Comment by SantosGuillamot** [comment] 2021-02-24 09:51
I've been taking a look at this and it seems this is possible in WordPress changing the permalinks like explained in [this guide](https://wpflux.com/14830-add-html-extension-wordpress-permalink-urls/).

Would it be enough to add that possibility in the [`wp-source` pattern](https://github.com/frontity/frontity/blob/dev/packages/wp-source/src/libraries/patterns/wp-org.ts#L78)?

I've done a quick test with the following pattern and it seems to work fine for me:

```
    pattern: "/(.*)?/:slug(\..*)?"

```

**Comment by luisherranz** [comment] 2021-02-24 12:14
Maybe the pattern should only do that for `\.html`? In case there is a `.jpg` or a `.json` that people don't want to relate to an HTML page?

```js
pattern: "/(.*)?/:slug(\.html)?"
```

**Comment by SantosGuillamot** [comment] 2021-02-26 12:29
>Maybe the pattern should only do that for \.html? In case there is a .jpg or a .json that people don't want to relate to an HTML page?

Sure. I did that because I saw that sometimes users use `.php` at the end of the urls, but I guess that case is even less common.

**Comment by luisherranz** [comment] 2021-02-27 07:40
Does that work? I thought `.php` extensions were only for php files.

**Comment by SantosGuillamot** [comment] 2021-03-01 09:05
I think you are right, they are for php files. Then I guess with `.html` is enough.

**Comment by luisherranz** [comment] 2021-03-02 09:38
I've just realized that people can also do this in their packages modifying their handlers in the `init` function:

<img width="775" alt="Screenshot 2021-03-02 at 10 34 34" src="https://user-images.githubusercontent.com/3305402/109628369-f7c6f000-7b42-11eb-8423-bdb83756673b.png">

```js
export default {
  actions: {
    myPackage: {
      init: ({ libraries }) => {
        libraries.source.handlers.map((handler) => {
          handler.pattern += "(\\.html)?";
          return handler;
        });
      },
    },
  },
};
```

So maybe we shouldn't complicate our default patterns for everyone else, don't you think?

I'll post the solution here as well: https://community.frontity.org/t/404-error-after-updating-original-post-from-wordpress-panel/3996/27

**Comment by cristianbote** [comment] 2021-03-02 10:04
That's a great solution @luisherranz! 😃  I knew there was something that I was missing out on. Do you think we could/should talk about these concepts in the docs? step by step tutorial?

**Comment by luisherranz** [comment] 2021-03-03 08:49
Haha, yes. Sometimes we forget how extensible Frontity is.

> Do you think we could/should talk about these concepts in the docs? step by step tutorial?

That's up to the DevRel team 🤷‍♂️ 😄 

---

Let's see if @hsbas can make this work and then we'll decide if we close this or not, ping the DevRel team and so on.

**Comment by SantosGuillamot** [comment] 2021-03-12 11:29
I posted this in the [community forum](https://community.frontity.org/t/wordpress-urls-ending-in-html/3996/40?u=santosguillamot), but I'll paste it here as well.

I think the issue is because we are using the [init function](https://docs.frontity.org/learning-frontity/actions#init-client-and-server), which doesn't guarantee that the libraries from other packages have been initialized. In this case the handlers from `wp-source`.

In Frontity, the packages are initialized in the order they are defined in the `frontity.settings.js` file. In the case of the default `mars-theme`, the [theme is before the wp-source package](https://github.com/frontity/frontity/blob/dev/projects/mars-theme/frontity.settings.js). This means that when we call the init function of the theme, the handlers don't exist yet.

There are two easy ways of solving this:
* Use the [beforeSSR action](https://docs.frontity.org/learning-frontity/actions#beforessr-server-only-__) instead of init:
```js
export default {
  actions: {
    myPackage: {
      beforeSSR: ({ libraries }) => {
        libraries.source.handlers.map((handler) => {
          handler.pattern += "(\\.html)?";
          return handler;
        });
      },
    },
  },
};

```

* Move the `wp-source` package to the top of the `frontity.settings.js` file so it is initialized before the theme.

I've tested both and they seem to work fine for me, but I guess that using `beforeSSR` is safer right?

**Comment by SantosGuillamot** [comment] 2021-03-16 09:15
I have been testing the different possibilities mentioned here and I found the same problem in all of them: the SSR only works for the archive pages and the latest post. If I try to SSR another post, it returns a 404. I think it isn't related to the `slug`, the title, or the content of the post because if I create a new post, the new one works but the old one stops working.

Do you have any clue why this could happen?

These are the approaches I tried:
1. Changing the pattern in `wp-source`:
```js
{
    name: "post type",
    priority: 30,
    pattern: "/(.*)?/:slug(\.html)?", // post or page or attachment
    func: postType,
}
```
2. As suggested by @luisherranz  [here](https://github.com/frontity/frontity/issues/727#issuecomment-788769414), I modified the pattern in the `init` function and I reordered the package so `wp-source` is initialized first.

3. I used `beforeSSR` instead of init.

**Comment by luisherranz** [comment] 2021-03-17 16:04
I have made a video to explain how this type of URLs can be configured and I posted it in the community thread: https://community.frontity.org/t/wordpress-urls-ending-in-html/3996/50

I am going to close this issue now because supporting `.html` ending URLs in all the handlers doesn't seem like something Frontity should do by default. It won't even be useful in this case because the URLs of @hsbas' site are more complex than just adding `.html` (as explained in the video).

@SantosGuillamot, @hsbas: If you don't agree feel free to reopen the issue and we can keep discussing it 🙂

**Closed as completed by luisherranz** 2021-03-17 16:04 UTC
Labels: bug, good first issue, priority: medium
