### ISSUE TITLE
Switched from Chakra to Mars theme to avoid one issue and faced another

### ISSUE THREAD

**Issue by warlockeg** [frontity/frontity#443] opened 2020-05-24 01:35 UTC
i tried to install Chakra UI then switched back to Mars theme on [Visit Guide](www.visit.guide) - Hint: its RTL Arabic website.

I faced the exact same issue here https://github.com/frontity/frontity/issues/200 and you can see it anytime on my localhost using team viewer!

Extra bug I noticed here also: https://github.com/frontity/frontity/issues/442

Home page works fine, categories don't and posts don't ( INTERNAL SERVER ERROR )

TypeError: Cannot read property 'split' of undefined
at webpack_exports.default (webpack-internal:///./node_modules/@frontity/wp-source/src/libraries/handlers/utils/capitalize.ts:2:73)
at Object.eval (webpack-internal:///./node_modules/@frontity/wp-source/src/libraries/handlers/taxonomy.ts:14:400)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at eval (webpack-internal:///./node_modules/@frontity/wp-source/src/actions.ts:18:101)

**Comment by warlockeg** [comment] 2020-05-24 01:36
my current config:

```
const settings = {
  "name": "visit-guide",
  "state": {
    "frontity": {
      "url": "https://www.visit.guide",
      "title": "دليل السفر",
      "description": "دليل المسافر العربي"
    }
  },
  "packages": [
    {
      "name": "@frontity/mars-theme",
      "state": {
        "theme": {
          "menu": [
            [
              "الرئيسية",
              "/"
            ],
            [
              "وجهات",
              "/category/destinations/"
            ],
            [
              "مصر",
              "/category/egypt/"
            ],
            [
              "شرم الشيخ",
              "/egypt/sharm-el-sheikh/"
            ],
            [
              "القاهرة",
              "/egypt/cairo/"
            ]
          ],
          "featured": {
            "showOnList": true,
            "showOnPost": true
          }
        }
      }
    },
    {
      "name": "@frontity/wp-source",
      "state": {
        "source": {
          "api": "https://www.visit.guide/wp-json"
        }
      }
    },
    "@frontity/tiny-router",
    "@frontity/html2react"
  ]
};

export default settings;
```

**Comment by DAreRodz** [comment] 2020-05-25 14:46
Taking a look at this issue.

**Comment by michalczaplinski** [comment] 2020-05-25 15:24
@DAreRodz FYI, This might be related to #432 (Special characters in permalink)

**Comment by DAreRodz** [comment] 2020-05-25 15:58
Thanks @michalczaplinski!

**Comment by DAreRodz** [comment] 2020-05-25 17:02
Ok, maybe it's not a bug and it's just a configuration problem.

It looks like categories in your site are not using a category base in their links (i.e. `/egypt/` instead of `/category/egypt`), so you have to set `"destinations"` and `"egypt"` in the menu settings.

Also, the default category handler<sup>1</sup> used by the `@frontity/wp-source` package doesn't know how to fetch categories without a category base, but don't worry, you can add a custom handler to fix that.

@warlockeg, please try the solution specified [here](https://community.frontity.org/t/how-to-remove-category-prefix-from-category-urls/817/2) in the Frontity community and let us know if it works. :slightly_smiling_face:

---

<sup>1</sup> Handlers are the piece of code that understand your site links and fetch all related entities for that link from the WP REST API. You can get more info in the [docs](https://docs.frontity.org/api-reference-1/wordpress-source#handlers).

**Comment by warlockeg** [comment] 2020-05-25 20:36
> Ok, maybe it's not a bug and it's just a configuration problem.
> 
> It looks like categories in your site are not using a category base in their links (i.e. `/egypt/` instead of `/category/egypt`), so you have to set `"destinations"` and `"egypt"` in the menu settings.
> 
> Also, the default category handler1 used by the `@frontity/wp-source` package doesn't know how to fetch categories without a category base, but don't worry, you can add a custom handler to fix that.
> 
> @warlockeg, please try the solution specified [here](https://community.frontity.org/t/how-to-remove-category-prefix-from-category-urls/817/2) in the Frontity community and let us know if it works. 🙂
> 
> 1 Handlers are the piece of code that understand your site links and fetch all related entities for that link from the WP REST API. You can get more info in the [docs](https://docs.frontity.org/api-reference-1/wordpress-source#handlers).

Thanks for your answer but it looks like its a bug, if it can not deal with WordPress then its a bug, i can not risk a production site depending on an unfinished technology, i will stick with WordPress till you guys release an update that WORKS, thanks!

**Comment by DAreRodz** [comment] 2020-05-26 12:41
@warlockeg did you try the solution I mentioned above?

I'm afraid I chose the wrong words :see_no_evil:. It's not that is not _working_ and you _fix_ it using the code I shared, it's the way Frontity works!

In order to handle cases where you have customized your WordPress site to change the category links you need to add some code in your theme.

**Comment by DAreRodz** [comment] 2020-05-26 18:06
Closing this, let's continue the conversation in the community topic!

https://community.frontity.org/t/internal-server-error-on-posts-only-using-chakra-ui-442/1913/3

I'll reopen the issue if this ends up being a bug.

**Closed as completed by DAreRodz** 2020-05-26 18:06 UTC
