### ISSUE TITLE
React composition events not working properly on controlled input fields (this events are needed to write languages like Japanese)

### ISSUE THREAD

**Issue by orballo** [frontity/frontity#519] opened 2020-07-20 04:02 UTC
**_Bug report_**

**Expected behavior**

When I start to type something in Japanese the `onCompositionStart` event should be triggered. Every new type should trigger a `onCompositionUpdate` event. And when I finish to type the word, a `onCompositionEnd` event should be triggered.

**Observed behavior**

Every time I type a character the three events are triggered together, therefor composition and writing in Japanese (or any other language that requires composition) is impossible.

**Steps involved to reproduce the problem**

You need to install a keyboard of a language that uses composition in order for it to work and then try to type something in a controlled input field.

I have an implementation using only `react-easy-state` and this problem doesn't exist, just in case this helps.

Let me know of anything else it might help.

**Possible solution**
I don't know what causes this.

Currently, a work around is using not controlled input fields.

**Comment by SantosGuillamot** [comment] 2020-07-21 07:43
Do you think it could be related to this other issue #236 somehow?

**Comment by orballo** [comment] 2020-07-21 08:22
I think it is possible. I thought you had that issue solved already with an update of other package.

**Comment by luisherranz** [comment] 2020-07-27 16:14
Once I finish this PR it will solve this issue https://github.com/frontity/frontity/pull/415.

I'm going to close this as a duplicate of https://github.com/frontity/frontity/issues/236 if you don't mind. Feel free to reopen if you think it's a different problem.

**Closed as completed by luisherranz** 2020-07-27 16:14 UTC
Labels: bug, duplicate
