### ISSUE TITLE
state.source.url turns case sensitive when in combination with other settings

### ISSUE THREAD

**Issue by alejosky** [frontity/frontity#665] opened 2021-01-14 18:28 UTC
**_Bug report_**

Following works (notice uppercase T)

`{
  "name": "@frontity/wp-source",
  "state": {
    "source": {
      "url": "http://localhost/Tele/"
    }
  }
}`

but in addition of other settings, as shown as follow, it stops working

`{
  "name": "@frontity/wp-source",
  "state": {
    "source": {
      "url": "http://localhost/Tele",
      "homepage": "/home"
    }
  }
}`

Then, it works fine again when the URL setting is written in lowercase

`{
  "name": "@frontity/wp-source",
  "state": {
    "source": {
      "url": "http://localhost/Tele",
      "homepage": "/home"
    }
  }
}`

**Expected behavior**

It should always work independently of letter cases.

**Observed behavior**

A 404 page not found error is shown on the website.

**Steps involved to reproduce the problem**

Use any URL with uppercase when homepage is also set.

**Info about your system**

## System:
 - OS: Windows 10 10.0.19042
 - CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor              
 - Memory: 2.59 GB / 31.93 GB
## Binaries:
 - Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
 - npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
## Browsers:
 - Chrome: Not Found
 - Edge: Spartan (44.19041.423.0), Chromium (87.0.664.75)
 - Internet Explorer: 11.0.19041.1
## npmPackages:
 - @frontity/core: ^1.9.1 => 1.9.1 
 - @frontity/head-tags: ^1.0.8 => 1.0.8 
 - @frontity/html2react: ^1.5.0 => 1.5.0 
 - @frontity/tiny-router: ^1.2.4 => 1.2.4 
 - @frontity/wp-source: ^1.10.0 => 1.10.0 
 - @frontity/zeitrelais: ./packages/zeitrelais => 1.4.4 
 - bootstrap: ^4.5.3 => 4.5.3 
 - frontity: ^1.13.0 => 1.13.0 
 - react-bootstrap: ^1.4.3 => 1.4.3 
 - react-bootstrap/AbstractNav:  undefined ()
 - react-bootstrap/AbstractNavItem:  undefined ()
 - react-bootstrap/Accordion:  undefined ()
 - react-bootstrap/AccordionCollapse:  undefined ()
 - react-bootstrap/AccordionContext:  undefined ()
 - react-bootstrap/AccordionToggle:  undefined ()
 - react-bootstrap/Alert:  undefined ()
 - react-bootstrap/Badge:  undefined ()
 - react-bootstrap/BootstrapModalManager:  undefined ()
 - react-bootstrap/Breadcrumb:  undefined ()
 - react-bootstrap/BreadcrumbItem:  undefined ()
 - react-bootstrap/Button:  undefined ()
 - react-bootstrap/ButtonGroup:  undefined ()
 - react-bootstrap/ButtonToolbar:  undefined ()
 - react-bootstrap/Card:  undefined ()
 - react-bootstrap/CardColumns:  undefined ()
 - react-bootstrap/CardContext:  undefined ()
 - react-bootstrap/CardDeck:  undefined ()
 - react-bootstrap/CardGroup:  undefined ()
 - react-bootstrap/CardImg:  undefined ()
 - react-bootstrap/Carousel:  undefined ()
 - react-bootstrap/CarouselCaption:  undefined ()
 - react-bootstrap/CarouselItem:  undefined ()
 - react-bootstrap/CloseButton:  undefined ()
 - react-bootstrap/Col:  undefined ()
 - react-bootstrap/Collapse:  undefined ()
 - react-bootstrap/Container:  undefined ()
 - react-bootstrap/Dropdown:  undefined ()
 - react-bootstrap/DropdownButton:  undefined ()
 - react-bootstrap/DropdownItem:  undefined ()
 - react-bootstrap/DropdownMenu:  undefined ()
 - react-bootstrap/DropdownToggle:  undefined ()
 - react-bootstrap/ElementChildren:  undefined ()
 - react-bootstrap/Fade:  undefined ()
 - react-bootstrap/Feedback:  undefined ()
 - react-bootstrap/Figure:  undefined ()
 - react-bootstrap/FigureCaption:  undefined ()
 - react-bootstrap/FigureImage:  undefined ()
 - react-bootstrap/Form:  undefined ()
 - react-bootstrap/FormCheck:  undefined ()
 - react-bootstrap/FormCheckInput:  undefined ()
 - react-bootstrap/FormCheckLabel:  undefined ()
 - react-bootstrap/FormContext:  undefined ()
 - react-bootstrap/FormControl:  undefined ()
 - react-bootstrap/FormFile:  undefined ()
 - react-bootstrap/FormFileInput:  undefined ()
 - react-bootstrap/FormFileLabel:  undefined ()
 - react-bootstrap/FormGroup:  undefined ()
 - react-bootstrap/FormLabel:  undefined ()
 - react-bootstrap/FormText:  undefined ()
 - react-bootstrap/Image:  undefined ()
 - react-bootstrap/InputGroup:  undefined ()
 - react-bootstrap/Jumbotron:  undefined ()
 - react-bootstrap/ListGroup:  undefined ()
 - react-bootstrap/ListGroupItem:  undefined ()
 - react-bootstrap/Media:  undefined ()
 - react-bootstrap/Modal:  undefined ()
 - react-bootstrap/ModalBody:  undefined ()
 - react-bootstrap/ModalContext:  undefined ()
 - react-bootstrap/ModalDialog:  undefined ()
 - react-bootstrap/ModalFooter:  undefined ()
 - react-bootstrap/ModalHeader:  undefined ()
 - react-bootstrap/ModalTitle:  undefined ()
 - react-bootstrap/Nav:  undefined ()
 - react-bootstrap/NavContext:  undefined ()
 - react-bootstrap/NavDropdown:  undefined ()
 - react-bootstrap/NavItem:  undefined ()
 - react-bootstrap/NavLink:  undefined ()
 - react-bootstrap/Navbar:  undefined ()
 - react-bootstrap/NavbarBrand:  undefined ()
 - react-bootstrap/NavbarCollapse:  undefined ()
 - react-bootstrap/NavbarContext:  undefined ()
 - react-bootstrap/NavbarToggle:  undefined ()
 - react-bootstrap/Overlay:  undefined ()
 - react-bootstrap/OverlayTrigger:  undefined ()
 - react-bootstrap/PageItem:  undefined ()
 - react-bootstrap/Pagination:  undefined ()
 - react-bootstrap/Popover:  undefined ()
 - react-bootstrap/PopoverContent:  undefined ()
 - react-bootstrap/PopoverTitle:  undefined ()
 - react-bootstrap/ProgressBar:  undefined ()
 - react-bootstrap/ResponsiveEmbed:  undefined ()
 - react-bootstrap/Row:  undefined ()
 - react-bootstrap/SafeAnchor:  undefined ()
 - react-bootstrap/SelectableContext:  undefined ()
 - react-bootstrap/Spinner:  undefined ()
 - react-bootstrap/SplitButton:  undefined ()
 - react-bootstrap/Switch:  undefined ()
 - react-bootstrap/Tab:  undefined ()
 - react-bootstrap/TabContainer:  undefined ()
 - react-bootstrap/TabContent:  undefined ()
 - react-bootstrap/TabContext:  undefined ()
 - react-bootstrap/TabPane:  undefined ()
 - react-bootstrap/Table:  undefined ()
 - react-bootstrap/Tabs:  undefined ()
 - react-bootstrap/ThemeProvider:  undefined ()
 - react-bootstrap/Toast:  undefined ()
 - react-bootstrap/ToastBody:  undefined ()
 - react-bootstrap/ToastContext:  undefined ()
 - react-bootstrap/ToastHeader:  undefined ()
 - react-bootstrap/ToggleButton:  undefined ()
 - react-bootstrap/ToggleButtonGroup:  undefined ()
 - react-bootstrap/Tooltip:  undefined ()
 - react-bootstrap/createChainedFunction:  undefined ()
 - react-bootstrap/createWithBsPrefix:  undefined ()
 - react-bootstrap/divWithClassName:  undefined ()
 - react-bootstrap/helpers:  undefined ()
 - react-bootstrap/triggerBrowserReflow:  undefined ()
 - react-bootstrap/types:  undefined ()
 - react-bootstrap/usePopperMarginModifiers:  undefined ()
 - react-bootstrap/useWrappedRefWithWarning:  undefined ()
 - react-slick: ^0.27.13 => 0.27.13 
## npmGlobalPackages:
 - frontity: Not Found
 - npx: Not Found

**Possible solution**

🤷‍♂️

**Comment by luisherranz** [comment] 2021-01-15 09:51
Thanks @alejosky, we will investigate the issue 🙂

_By the way, your theme dependencies (like bootstrap) should be declared on your theme's `package.json`, not on your project's `package.json`._

**Comment by DAreRodz** [comment] 2021-01-20 13:50
@alejosky, does it happen only with the homepage?

Also, did you set the **homepage** setting in the WordPress instance as well? It's explained [here](https://docs.frontity.org/api-reference-1/wordpress-source#state-source-homepage) in the `@frontity/wp-source` package documentation.

**Comment by alejosky** [comment] 2021-01-31 11:38
@DAreRodz No idea.

Also...
![image](https://user-images.githubusercontent.com/11649435/106382631-28d7c780-63c1-11eb-9e3e-0beeea7d6b97.png)

**Comment by alejosky** [comment] 2021-01-31 11:39
I am going to unsubscribe to this issue now. Good luck.

**Comment by DAreRodz** [comment] 2021-02-03 11:19
@alejosky I was able to reproduce the issue using a WordPress multisite setup.

The problem is in these lines of code, inside the `transformLink` function. That function is being used by the `@frontity/wp-source` package to transform the links of fetched entities so they point to Frontity instead of WordPress.

https://github.com/frontity/frontity/blob/c139094e956d3119f9fd1ea2342717e29e187f2f/packages/wp-source/src/libraries/transform-link.ts#L56-L61

What is happening there it that the path of the site's subdirectory (`"/Tele"`) is obtained from the `state.source.url`prop (`"http://localhost/Tele"`)  and stored in `wpPath`, and that value is replaced in the entity link with the Frontity subdirectory.

As the `.replace()` function is case sensitive, `wpPath` is not found in links -because WordPress ensures all links are lowercase (`"http://localhost/tele/hello-world"`) and `wpPath` is uppercase (`"/Tele"`)-, and so they are not transformed properly.

That makes Frontity unable to find the data of any link and return 404 errors.

A way to solve this would be to build a regexp from `wpPath` with the case-insensitive flag, and use it instead of `wpPath` directly. Something like:

```ts
entity.link = entity.link.replace(
  new RegExp(`^${wpPath.replace("/", "\\/")}`, "i"),
  subdirectory
);
```

In any case, the thing is that WordPress doesn't allow sites to have a subdirectory with capital letters, so I don't think this is a big problem. It would be easily avoided just typing the `state.source.url` props without capital letters. @alejosky, do you need that URL to be uppercased for some reason?

![Screenshot from 2021-02-03 11-41-44](https://user-images.githubusercontent.com/6917969/106738544-55d1e780-6618-11eb-8864-004f12967875.png)

@SantosGuillamot, feel free to assign this issue the priority you think appropriate.

**Comment by SantosGuillamot** [comment] 2021-02-08 07:35
>In any case, the thing is that WordPress doesn't allow sites to have a subdirectory with capital letters

If WordPress doesn't allow to have capital letters I am not sure if we should allow it from Frontity or just throw a warning. What do you think?

**Comment by luisherranz** [comment] 2021-02-09 17:02
I don't think we need to support things that not even WordPress supports.

**Comment by SantosGuillamot** [comment] 2021-02-12 08:50
Yes, I agree. Should we close this then?

**Comment by luisherranz** [comment] 2021-02-16 08:01
Sure. Done 🙂

**Closed as completed by luisherranz** 2021-02-16 08:01 UTC
Labels: bug, awaiting-priority
