### ISSUE TITLE
Problems with global links

### ISSUE THREAD

**Issue by dmitrydrynov** [frontity/frontity#346] opened 2020-03-19 20:00 UTC
**Describe the expected behavior**

Links in the article are displayed incorrectly.
I need as here
![image](https://user-images.githubusercontent.com/4089575/77109731-88411900-6a35-11ea-8f6a-56a620b38c2d.png)

**Describe the observed behavior**
I get as here
![image](https://user-images.githubusercontent.com/4089575/77109633-4a43f500-6a35-11ea-9518-aa693e1e3b1f.png)

console.log(post.content.rendered) return
![image](https://user-images.githubusercontent.com/4089575/77110005-f1289100-6a35-11ea-9eb0-69a8e74f79cb.png)

**Describe the steps involved to reproduce the problem**

Change source api on fronity.settings.js to my "https://polygon.by/wp-json"

**Add info about your system**

## System:
 - OS: Windows 10 10.0.18363
 - CPU: (8) x64 Intel(R) Core(TM) i7-6770HQ CPU @ 2.60GHz
 - Memory: 1.35 GB / 7.89 GB
## Binaries:
 - Node: 10.15.1 - C:\Program Files\nodejs\node.EXE
 - npm: 6.13.7 - C:\Program Files\nodejs\npm.CMD
## Browsers:
 - Edge: 44.18362.449.0
 - Internet Explorer: 11.0.18362.1
## npmPackages:
 - frontity: ^1.5.2 => 1.5.2
## npmGlobalPackages:
 - frontity: Not Found
 - npx: Not Found

**Comment by luisherranz** [comment] 2020-03-20 16:00
Hey @dmitrydrynov, welcome to Frontity 🙂 

I'm taking a look at it looks to me that the problem is the output of your REST API. For example, for a post https://polygon.by/wp-json/wp/v2/posts/19811, the `href` attribute of anchors don't have any type of quote:

```html
<div class="lL" style="max-width:100%;width:1280px;margin:5px;">
  Watch this video 
  <a href=https://youtu.be/IBsJ4HXoqDw>on YouTube</a>
</div>
```

That is not valid HTML.

Html2React uses a library called [Himalaya](https://github.com/andrejewski/himalaya) internally, that you can try online here: https://jew.ski/himalaya/

If you copy and paste your HTML, you'll see that it's not valid and returns `https:` as the value of `href`:

```js
{
  "type": "element",
  "tagName": "a",
  "attributes": [
    {
      "key": "href",
      "value": "https:" // <- Wrong value.
    }
  ],
  "children": []
}
```

I think the best solution would be to inspect why your WordPress is outputting invalid HTML. Check your database to see if those links don't have quotes there.
- If they don't have quotes, then it's probably an error on a plugin or a filter that works before you save those links, in the post editor.
- If they have quotes, then it's probably some type of filter that is messing your content output.

I'm going to close this as there's not a problem related to Frontity, but feel free to repone if you discover something else.

**Closed as completed by luisherranz** 2020-03-20 16:00 UTC
